version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
      - "15675:15675"   # WebSocket port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
